# -*- coding: utf-8 -*-
"""part1_data_prep.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12u_TELS_QazJA76EZ0jwFRWGdi3fIUr1
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import numpy as np
import pandas as pd

# Set random seed for reproducibility
np.random.seed(42)
n_samples = 1000

# 1. Generate base features
age = np.random.randint(18, 70, size=n_samples)
income = np.random.exponential(scale=50000, size=n_samples) + 15000  # Highly right-skewed
satisfaction_score = np.random.uniform(1, 10, size=n_samples)

# Non-linear monotonic relationship (Perfect for Spearman vs Pearson task)
# y = x^3 creates a strong monotonic but non-linear relationship
engagement_index = (satisfaction_score ** 3) + np.random.normal(0, 50, size=n_samples)

# Categorical column with repetitive strings
department = np.random.choice(["Sales", "Engineering", "Marketing", "HR"], size=n_samples, p=[0.4, 0.3, 0.2, 0.1])

# 2. Create DataFrame
df = pd.DataFrame(
    {
        "Age": age,
        "Income": income,
        "Satisfaction_Score": satisfaction_score,
        "Engagement_Index": engagement_index,
        "Department": department,
    }
)

# 3. Inject wrong data types (Task 4 requirement: numeric stored as object)
# We will turn 'Age' into strings and add an occasional corrupt value
df["Age"] = df["Age"].astype(str)
df.iloc[42, df.columns.get_loc("Age")] = "Unknown"  # Forces object type

# 4. Inject highly skewed columns (Task 5 & 9a requirement)
# 'Income' is already highly exponentially skewed. Let's make another one:
df["Debt_Ratio"] = np.random.lognormal(mean=0, sigma=1, size=n_samples)

# 5. Inject outliers (Task 6 requirement)
# Add massive outliers to Income
df.iloc[[10, 50, 100, 200], df.columns.get_loc("Income")] = [500000, 600000, 750000, 900000]

# 6. Inject Null Values (Task 2 requirement)
# Column with > 20% nulls
df["Survey_Feedback"] = np.random.choice(
    [np.nan, "Good", "Bad", "Average"], size=n_samples, p=[0.25, 0.25, 0.25, 0.25]
)
# Columns with < 20% nulls (to be filled with median)
df.loc[df.sample(frac=0.05).index, "Income"] = np.nan
df.loc[df.sample(frac=0.08).index, "Debt_Ratio"] = np.nan

# 7. Inject Duplicates (Task 3 requirement)
duplicate_rows = df.iloc[[1, 2, 3, 4, 5]].copy()
df = pd.concat([df, duplicate_rows], ignore_index=True)

# Save to CSV
df.to_csv("your_dataset.csv", index=False)
print("Successfully generated 'your_dataset.csv' with all required assignment edge cases!")

# Convert 'Age' back to numeric and coerce 'Unknown' to NaN
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")
# Convert 'Department' to category
df["Department"] = df["Department"].astype("category")

# Use 'Department' as your categorical column
categorical_col = "Department"

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# ==========================================
# Task 1: Load the dataset
# ==========================================
print("--- Task 1: Data Loading ---")
# TODO: Replace with your actual file path
df = pd.read_csv('your_dataset.csv')

print("First 5 rows:")
display(df.head())
print("\nData Types:")
print(df.dtypes)
print("\nDataFrame Shape:", df.shape)

# ==========================================
# Task 2: Null value analysis
# ==========================================
print("\n--- Task 2: Null Value Analysis ---")
null_counts = df.isnull().sum()
null_percentages = (null_counts / df.shape[0]) * 100
null_summary = pd.DataFrame({'Null Count': null_counts, 'Null Percentage': null_percentages})
print("Null Percentage Table:")
print(null_summary)

print("\nColumns exceeding 20% null rate:")
print(null_percentages[null_percentages > 20])

# Impute numeric columns with < 20% nulls
numeric_cols = df.select_dtypes(include=[np.number]).columns
for col in numeric_cols:
    if 0 < null_percentages[col] <= 20:
        median_val = df[col].median()
        df[col] = df[col].fillna(median_val)
        print(f"Filled nulls in '{col}' with median: {median_val}")

# ==========================================
# Task 3: Duplicate detection and removal
# ==========================================
print("\n--- Task 3: Duplicate Detection ---")
duplicate_count = df.duplicated().sum()
print(f"Number of duplicate rows: {duplicate_count}")

# Store null percentage before dropping to compare
null_pct_before = (df.isnull().sum() / df.shape[0]) * 100

df = df.drop_duplicates()
print(f"Rows remaining after dropping duplicates: {df.shape[0]}")

null_pct_after = (df.isnull().sum() / df.shape[0]) * 100
null_pct_change = null_pct_after - null_pct_before
print("\nChange in null percentage after duplicate removal:")
print(null_pct_change[null_pct_change != 0].dropna())

# ==========================================
# Task 4: Data type correction
# ==========================================
print("\n--- Task 4: Data Type Correction ---")
print("Memory usage BEFORE conversion:")
print(df.memory_usage(deep=True).sum(), "bytes")

# TODO: Replace 'numeric_col_as_object' with a column that needs numeric conversion
# df['numeric_col_as_object'] = pd.to_numeric(df['numeric_col_as_object'], errors='coerce')

# TODO: Replace 'string_col_to_category' with a repetitive string column
# df['string_col_to_category'] = df['string_col_to_category'].astype('category')

print("Memory usage AFTER conversion:")
print(df.memory_usage(deep=True).sum(), "bytes")

# ==========================================
# Task 5: Descriptive statistics and skewness
# ==========================================
print("\n--- Task 5: Descriptive Stats & Skewness ---")
print("Descriptive Statistics:")
display(df.describe())

print("\nSkewness of numeric columns:")
skewness = df[numeric_cols].skew()
print(skewness)

highest_skew_col = skewness.abs().idxmax()
print(f"\nColumn with highest absolute skewness: {highest_skew_col} (Skew: {skewness[highest_skew_col]:.4f})")

# ==========================================
# Task 6: Outlier detection with IQR
# ==========================================
print("\n--- Task 6: Outlier Detection ---")
# TODO: Choose two numeric columns for outlier detection
cols_for_outliers = [numeric_cols[0], numeric_cols[1]]

for col in cols_for_outliers:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]
    print(f"Column '{col}': {len(outliers)} outliers detected.")

# ==========================================
# Task 7: Visualizations
# ==========================================
print("\n--- Task 7: Visualizations ---")
plt.figure(figsize=(15, 10))

# 1. Line plot
plt.subplot(2, 3, 1)
# TODO: Replace 'numeric_cols[0]' with your desired column
plt.plot(df.index, df[numeric_cols[0]])
plt.title(f'Line Plot of {numeric_cols[0]}')
plt.xlabel('Index')
plt.ylabel(numeric_cols[0])

# 2. Bar chart
plt.subplot(2, 3, 2)
# TODO: Replace categorical/numeric cols
# categorical_col = 'your_cat_col'
# df.groupby(categorical_col)[numeric_cols[1]].mean().plot.bar()
# plt.title(f'Mean {numeric_cols[1]} by {categorical_col}')

# 3. Histogram of most skewed column
plt.subplot(2, 3, 3)
sns.histplot(df[highest_skew_col], bins=20)
plt.title(f'Histogram of {highest_skew_col}')

# 4. Scatter plot
plt.subplot(2, 3, 4)
# TODO: Replace with two columns you expect to be correlated
sns.scatterplot(x=df[numeric_cols[0]], y=df[numeric_cols[1]])
plt.title(f'Scatter: {numeric_cols[0]} vs {numeric_cols[1]}')

# 5. Box plot
plt.subplot(2, 3, 5)
# TODO: Replace 'your_cat_col' and 'numeric_cols[0]'
# sns.boxplot(x=df['your_cat_col'], y=df[numeric_cols[0]])
# plt.title('Box plot by Category')

plt.tight_layout()
plt.show()

# ==========================================
# Task 8: Correlation heat map
# ==========================================
print("\n--- Task 8: Correlation Heat Map ---")
pearson_corr = df[numeric_cols].corr()

plt.figure(figsize=(10, 8))
sns.heatmap(pearson_corr, annot=True, cmap='coolwarm', fmt=".2f")
plt.title("Pearson Correlation Heatmap")
plt.show()

# Extracting highest absolute correlation
corr_unstacked = pearson_corr.abs().unstack()
corr_unstacked = corr_unstacked[corr_unstacked < 1.0] # Exclude self-correlation
top_corr_pair = corr_unstacked.idxmax()
print(f"Highest absolute correlation pair: {top_corr_pair} (Value: {corr_unstacked.max():.4f})")

# ==========================================
# Task 9a: Imputation strategy comparison
# ==========================================
print("\n--- Task 9a: Imputation Strategy Comparison ---")
top_2_skewed = skewness.abs().nlargest(2).index

for col in top_2_skewed:
    col_mean = df[col].mean()
    col_median = df[col].median()
    print(f"Column '{col}': Mean = {col_mean:.4f}, Median = {col_median:.4f}")

    # Impute remaining nulls (if any) with the median
    df[col] = df[col].fillna(col_median)

print("\nNulls remaining in top skewed columns after imputation:")
print(df[top_2_skewed].isnull().sum())

# ==========================================
# Task 9b: Spearman rank correlation
# ==========================================
print("\n--- Task 9b: Spearman Rank Correlation ---")
spearman_corr = df[numeric_cols].corr(method='spearman')

print("Spearman Correlation Matrix:")
display(spearman_corr)

diff_matrix = (spearman_corr - pearson_corr).abs()
print("\nAbsolute Difference Matrix (|Spearman - Pearson|):")
display(diff_matrix)

# Get top 3 column pairs with largest difference
diff_unstacked = diff_matrix.unstack()
diff_unstacked = diff_unstacked[diff_unstacked < 1.0].drop_duplicates()
top_3_diffs = diff_unstacked.nlargest(3)
print("\nTop 3 column pairs with largest |Spearman - Pearson| difference:")
print(top_3_diffs)

# ==========================================
# Task 9c: Grouped aggregation
# ==========================================
print("\n--- Task 9c: Grouped Aggregation ---")
# TODO: Replace with your actual categorical and numeric column
cat_col = df.select_dtypes(include=['category', 'object']).columns[0] # taking first string col as fallback
num_col = numeric_cols[0]

grouped_agg = df.groupby(cat_col)[num_col].agg(['mean', 'std', 'count'])
print(f"Grouped Aggregation ({num_col} grouped by {cat_col}):")
print(grouped_agg)

# ==========================================
# Task 10: Save clean dataset
# ==========================================
print("\n--- Task 10: Saving Data ---")
df.to_csv('cleaned_data.csv', index=False)
print("Data saved successfully to 'cleaned_data.csv'")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression, Ridge, LogisticRegression
from sklearn.metrics import (
    mean_squared_error,
    r2_score,
    confusion_matrix,
    classification_report,
    roc_curve,
    roc_auc_score,
    precision_score,
    recall_score,
    f1_score
)

# ==========================================
# Task 1: Load Data & Define Targets
# ==========================================
print("--- Task 1: Setup ---")
df = pd.read_csv('cleaned_data.csv')

# TODO: Define your target regression column here
target_col = 'Income' # Replace with your actual continuous column

# Define X (features) and y_reg (regression target)
X = df.drop(columns=[target_col])
y_reg = df[target_col]

# Define y_clf (classification target) - Binarizing at the median
y_clf = (y_reg > y_reg.median()).astype(int)

# ==========================================
# Task 2: Encode Categorical Columns
# ==========================================
print("\n--- Task 2: Encoding ---")
# Example of Manual Ordinal Encoding (Uncomment and modify if you have ordinal data)
# ordinal_mapping = {'Low': 1, 'Medium': 2, 'High': 3}
# if 'Ordinal_Column' in X.columns:
#     X['Ordinal_Column'] = X['Ordinal_Column'].map(ordinal_mapping)

# One-hot encoding for nominal categories (dropping first to avoid multicollinearity)
X = pd.get_dummies(X, drop_first=True)
print("Features after encoding:", X.shape[1])

# ==========================================
# Task 3: Leak-free Train-Test Split & Scaling
# ==========================================
print("\n--- Task 3: Split & Scale ---")
# Split the data (Note: we split both y_reg and y_clf simultaneously)
X_train, X_test, y_reg_train, y_reg_test, y_clf_train, y_clf_test = train_test_split(
    X, y_reg, y_clf, test_size=0.2, random_state=42
)

# Fit scaler strictly on training data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test) # Transform test data using train parameters

# ==========================================
# Task 4: Regression Model - Linear Regression
# ==========================================
print("\n--- Task 4: Linear & Ridge Regression ---")
# 1. OLS Linear Regression
lr = LinearRegression()
lr.fit(X_train_scaled, y_reg_train)
y_pred_reg = lr.predict(X_test_scaled)

mse_lr = mean_squared_error(y_reg_test, y_pred_reg)
r2_lr = r2_score(y_reg_test, y_pred_reg)
print(f"OLS Linear Regression - MSE: {mse_lr:.4f}, R2: {r2_lr:.4f}")

# Coefficients
coef_df = pd.DataFrame({'Feature': X.columns, 'Coefficient': lr.coef_})
coef_df['Abs_Coef'] = coef_df['Coefficient'].abs()
top_3_features = coef_df.nlargest(3, 'Abs_Coef')
print("\nTop 3 Largest Coefficients (Absolute Value):")
print(top_3_features[['Feature', 'Coefficient']])

# 2. Ridge Regression
ridge = Ridge(alpha=1.0)
ridge.fit(X_train_scaled, y_reg_train)
y_pred_ridge = ridge.predict(X_test_scaled)

mse_ridge = mean_squared_error(y_reg_test, y_pred_ridge)
r2_ridge = r2_score(y_reg_test, y_pred_ridge)
print(f"\nRidge Regression - MSE: {mse_ridge:.4f}, R2: {r2_ridge:.4f}")

# ==========================================
# Task 5a: Classification Model - Logistic Reg
# ==========================================
print("\n--- Task 5a: Logistic Regression ---")
# Check class imbalance
class_distribution = y_clf_train.value_counts(normalize=True)
print(f"Class distribution in training set:\n{class_distribution}")

# Automatically apply class_weight if minority class < 35%
class_weight_param = 'balanced' if class_distribution.min() < 0.35 else None
if class_weight_param:
    print("Class imbalance detected (minority < 35%). Using class_weight='balanced'.")

log_reg = LogisticRegression(max_iter=1000, class_weight=class_weight_param)
log_reg.fit(X_train_scaled, y_clf_train)

y_pred_clf = log_reg.predict(X_test_scaled)
y_prob_clf = log_reg.predict_proba(X_test_scaled)[:, 1]

print("\nConfusion Matrix:")
print(confusion_matrix(y_clf_test, y_pred_clf))
print("\nClassification Report:")
print(classification_report(y_clf_test, y_pred_clf))

auc_log = roc_auc_score(y_clf_test, y_prob_clf)
print(f"ROC AUC Score: {auc_log:.4f}")

# Plot ROC Curve
fpr, tpr, _ = roc_curve(y_clf_test, y_prob_clf)
plt.figure(figsize=(8, 6))
plt.plot(fpr, tpr, label=f'Logistic Regression (AUC = {auc_log:.2f})')
plt.plot([0, 1], [0, 1], 'k--', label='Random Guess')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve')
plt.legend()
plt.show()

# ==========================================
# Task 5b: Decision-Threshold Sensitivity
# ==========================================
print("\n--- Task 5b: Decision Thresholds ---")
thresholds = [0.30, 0.40, 0.50, 0.60, 0.70]
results = []

for t in thresholds:
    t_preds = (y_prob_clf >= t).astype(int)
    results.append({
        'Threshold': t,
        'Recall': recall_score(y_clf_test, t_preds),
        'Precision': precision_score(y_clf_test, t_preds),
        'F1': f1_score(y_clf_test, t_preds)
    })

threshold_df = pd.DataFrame(results)
print(threshold_df.to_string(index=False))

# ==========================================
# Task 6: Regularization Experiment
# ==========================================
print("\n--- Task 6: Regularization Experiment (C=0.01) ---")
log_reg_01 = LogisticRegression(C=0.01, max_iter=1000, class_weight=class_weight_param)
log_reg_01.fit(X_train_scaled, y_clf_train)

y_pred_01 = log_reg_01.predict(X_test_scaled)
y_prob_01 = log_reg_01.predict_proba(X_test_scaled)[:, 1]

auc_01 = roc_auc_score(y_clf_test, y_prob_01)
print(f"C=1.0  -> Precision: {precision_score(y_clf_test, y_pred_clf):.4f}, Recall: {recall_score(y_clf_test, y_pred_clf):.4f}, AUC: {auc_log:.4f}")
print(f"C=0.01 -> Precision: {precision_score(y_clf_test, y_pred_01):.4f}, Recall: {recall_score(y_clf_test, y_pred_01):.4f}, AUC: {auc_01:.4f}")

# ==========================================
# Task 7: Bootstrap Confidence Interval
# ==========================================
print("\n--- Task 7: Bootstrap Confidence Interval ---")
n_bootstraps = 500
auc_diffs = []
rng = np.random.RandomState(42)

for i in range(n_bootstraps):
    # Sample row indices with replacement
    indices = rng.choice(len(y_clf_test), size=len(y_clf_test), replace=True)

    # Extract sampled truth and probabilities
    y_true_b = y_clf_test.iloc[indices]
    y_prob_1_b = y_prob_clf[indices]
    y_prob_01_b = y_prob_01[indices]

    # Skip iteration if the bootstrap sample contains only one class
    if len(np.unique(y_true_b)) < 2:
        continue

    # Compute AUC for both models on this sample
    auc_1_b = roc_auc_score(y_true_b, y_prob_1_b)
    auc_01_b = roc_auc_score(y_true_b, y_prob_01_b)

    # Append difference (C=1.0 minus C=0.01)
    auc_diffs.append(auc_1_b - auc_01_b)

mean_diff = np.mean(auc_diffs)
ci_lower = np.percentile(auc_diffs, 2.5)
ci_upper = np.percentile(auc_diffs, 97.5)

print(f"Mean AUC Difference: {mean_diff:.4f}")
print(f"95% Confidence Interval: [{ci_lower:.4f}, {ci_upper:.4f}]")

import pandas as pd
import numpy as np
import joblib
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.model_selection import StratifiedKFold, cross_val_score, GridSearchCV
from sklearn.pipeline import make_pipeline
from sklearn.impute import SimpleImputer
from sklearn.metrics import accuracy_score, roc_auc_score

# Ensure variables from Part 2 exist (X_train, X_test, X_train_scaled, X_test_scaled, y_clf_train, y_clf_test)

# ==========================================
# Task 1: Decision Tree Baseline
# ==========================================
print("\n--- Task 1: Baseline Decision Tree ---")
dt_base = DecisionTreeClassifier(random_state=42)
dt_base.fit(X_train_scaled, y_clf_train)

print(f"Train Accuracy: {accuracy_score(y_clf_train, dt_base.predict(X_train_scaled)):.4f}")
print(f"Test Accuracy:  {accuracy_score(y_clf_test, dt_base.predict(X_test_scaled)):.4f}")

# ==========================================
# Task 2: Controlled Decision Tree
# ==========================================
print("\n--- Task 2: Controlled Decision Tree ---")
dt_controlled = DecisionTreeClassifier(max_depth=5, min_samples_split=20, random_state=42)
dt_controlled.fit(X_train_scaled, y_clf_train)

print(f"Train Accuracy: {accuracy_score(y_clf_train, dt_controlled.predict(X_train_scaled)):.4f}")
print(f"Test Accuracy:  {accuracy_score(y_clf_test, dt_controlled.predict(X_test_scaled)):.4f}")

# ==========================================
# Task 3: Gini vs Entropy
# ==========================================
print("\n--- Task 3: Gini vs Entropy ---")
dt_gini = DecisionTreeClassifier(criterion='gini', max_depth=5, random_state=42)
dt_gini.fit(X_train_scaled, y_clf_train)

dt_entropy = DecisionTreeClassifier(criterion='entropy', max_depth=5, random_state=42)
dt_entropy.fit(X_train_scaled, y_clf_train)

print(f"Gini Test Accuracy:    {accuracy_score(y_clf_test, dt_gini.predict(X_test_scaled)):.4f}")
print(f"Entropy Test Accuracy: {accuracy_score(y_clf_test, dt_entropy.predict(X_test_scaled)):.4f}")

# ==========================================
# Task 4: Random Forest
# ==========================================
print("\n--- Task 4: Random Forest ---")
rf = RandomForestClassifier(n_estimators=100, max_depth=10, random_state=42)
rf.fit(X_train_scaled, y_clf_train)

rf_train_acc = accuracy_score(y_clf_train, rf.predict(X_train_scaled))
rf_test_acc = accuracy_score(y_clf_test, rf.predict(X_test_scaled))
rf_roc_auc = roc_auc_score(y_clf_test, rf.predict_proba(X_test_scaled)[:, 1])

print(f"RF Train Accuracy: {rf_train_acc:.4f}")
print(f"RF Test Accuracy:  {rf_test_acc:.4f}")
print(f"RF Test ROC-AUC:   {rf_roc_auc:.4f}")

feature_importances = pd.Series(rf.feature_importances_, index=X_train.columns)
print("\nTop 5 Features by Importance:")
print(feature_importances.nlargest(5))

# ==========================================
# Task 4a: Gradient Boosting
# ==========================================
print("\n--- Task 4a: Gradient Boosting ---")
gb = GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, max_depth=3, random_state=42)
gb.fit(X_train_scaled, y_clf_train)

print(f"GB Train Accuracy: {accuracy_score(y_clf_train, gb.predict(X_train_scaled)):.4f}")
print(f"GB Test Accuracy:  {accuracy_score(y_clf_test, gb.predict(X_test_scaled)):.4f}")
print(f"GB Test ROC-AUC:   {roc_auc_score(y_clf_test, gb.predict_proba(X_test_scaled)[:, 1]):.4f}")

# ==========================================
# Task 4b: Feature Ablation Study
# ==========================================
print("\n--- Task 4b: Feature Ablation ---")
lowest_5_features = feature_importances.nsmallest(5).index
print(f"Removing lowest 5 features: {list(lowest_5_features)}")

# Get column indices to drop from the scaled numpy arrays
drop_indices = [X_train.columns.get_loc(col) for col in lowest_5_features]
X_train_reduced = np.delete(X_train_scaled, drop_indices, axis=1)
X_test_reduced = np.delete(X_test_scaled, drop_indices, axis=1)

rf_reduced = RandomForestClassifier(n_estimators=100, max_depth=10, random_state=42)
rf_reduced.fit(X_train_reduced, y_clf_train)
rf_reduced_auc = roc_auc_score(y_clf_test, rf_reduced.predict_proba(X_test_reduced)[:, 1])

print(f"Full Model Test AUC:    {rf_roc_auc:.4f}")
print(f"Reduced Model Test AUC: {rf_reduced_auc:.4f}")

# ==========================================
# Task 5: Cross-Validated Comparison
# ==========================================
print("\n--- Task 5: Cross-Validation ---")
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

models = {
    'Logistic Regression': log_reg, # Assumes log_reg from Part 2 is still in memory
    'Controlled DT': dt_controlled,
    'Random Forest': rf,
    'Gradient Boosting': gb
}

for name, model in models.items():
    scores = cross_val_score(model, X_train_scaled, y_clf_train, cv=cv, scoring='roc_auc')
    print(f"{name} - 5-Fold AUC: {scores.mean():.4f} (+/- {scores.std():.4f})")

# ==========================================
# Task 6: Hyperparameter Tuning (GridSearchCV)
# ==========================================
print("\n--- Task 6: GridSearchCV ---")
param_grid = {
    'randomforestclassifier__n_estimators': [50, 100, 200],
    'randomforestclassifier__max_depth': [5, 10, None],
    'randomforestclassifier__min_samples_leaf': [1, 5]
}

pipeline = make_pipeline(
    SimpleImputer(strategy='median'),
    StandardScaler(),
    RandomForestClassifier(random_state=42)
)

grid_search = GridSearchCV(
    pipeline, param_grid, cv=StratifiedKFold(n_splits=5, shuffle=True, random_state=42),
    scoring='roc_auc', n_jobs=-1
)

# Note: We fit on UNSCALED data because the pipeline handles the scaling
grid_search.fit(X_train, y_clf_train)

print(f"Best Parameters: {grid_search.best_params_}")
print(f"Best CV ROC-AUC: {grid_search.best_score_:.4f}")

best_pipeline = grid_search.best_estimator_

# ==========================================
# Task 7: Manual Learning Curve
# ==========================================
print("\n--- Task 7: Manual Learning Curve ---")
fractions = [0.2, 0.4, 0.6, 0.8, 1.0]
results = []

for f in fractions:
    n_samples = int(f * len(X_train))
    X_subset = X_train.iloc[:n_samples]
    y_subset = y_clf_train.iloc[:n_samples]

    # Fit the best pipeline on the subset
    best_pipeline.fit(X_subset, y_subset)

    # Train AUC (evaluated on the subset)
    train_prob = best_pipeline.predict_proba(X_subset)[:, 1]
    train_auc = roc_auc_score(y_subset, train_prob)

    # Test AUC (evaluated on fixed full test set)
    # Using X_test (unscaled) because the pipeline handles scaling internally
    test_prob = best_pipeline.predict_proba(X_test)[:, 1]
    test_auc = roc_auc_score(y_clf_test, test_prob)

    results.append({'Training Fraction': f, 'Training AUC': train_auc, 'Test AUC': test_auc})

lc_df = pd.DataFrame(results)
print(lc_df.to_string(index=False))

# ==========================================
# Task 8: Serialize Best Model
# ==========================================
print("\n--- Task 8: Model Serialization ---")
joblib.dump(best_pipeline, 'best_model.pkl')
print("Model saved to 'best_model.pkl'")

# Reload and predict block
loaded_model = joblib.load('best_model.pkl')
hand_crafted_rows = X_test.iloc[:2] # Taking 2 real rows as dummy input
predictions = loaded_model.predict(hand_crafted_rows)
print(f"Predictions on 2 hand-crafted rows: {predictions}")