# -*- coding: utf-8 -*-
"""part1_data_prep.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12u_TELS_QazJA76EZ0jwFRWGdi3fIUr1
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import numpy as np
import pandas as pd

# Set random seed for reproducibility
np.random.seed(42)
n_samples = 1000

# 1. Generate base features
age = np.random.randint(18, 70, size=n_samples)
income = np.random.exponential(scale=50000, size=n_samples) + 15000  # Highly right-skewed
satisfaction_score = np.random.uniform(1, 10, size=n_samples)

# Non-linear monotonic relationship (Perfect for Spearman vs Pearson task)
# y = x^3 creates a strong monotonic but non-linear relationship
engagement_index = (satisfaction_score ** 3) + np.random.normal(0, 50, size=n_samples)

# Categorical column with repetitive strings
department = np.random.choice(["Sales", "Engineering", "Marketing", "HR"], size=n_samples, p=[0.4, 0.3, 0.2, 0.1])

# 2. Create DataFrame
df = pd.DataFrame(
    {
        "Age": age,
        "Income": income,
        "Satisfaction_Score": satisfaction_score,
        "Engagement_Index": engagement_index,
        "Department": department,
    }
)

# 3. Inject wrong data types (Task 4 requirement: numeric stored as object)
# We will turn 'Age' into strings and add an occasional corrupt value
df["Age"] = df["Age"].astype(str)
df.iloc[42, df.columns.get_loc("Age")] = "Unknown"  # Forces object type

# 4. Inject highly skewed columns (Task 5 & 9a requirement)
# 'Income' is already highly exponentially skewed. Let's make another one:
df["Debt_Ratio"] = np.random.lognormal(mean=0, sigma=1, size=n_samples)

# 5. Inject outliers (Task 6 requirement)
# Add massive outliers to Income
df.iloc[[10, 50, 100, 200], df.columns.get_loc("Income")] = [500000, 600000, 750000, 900000]

# 6. Inject Null Values (Task 2 requirement)
# Column with > 20% nulls
df["Survey_Feedback"] = np.random.choice(
    [np.nan, "Good", "Bad", "Average"], size=n_samples, p=[0.25, 0.25, 0.25, 0.25]
)
# Columns with < 20% nulls (to be filled with median)
df.loc[df.sample(frac=0.05).index, "Income"] = np.nan
df.loc[df.sample(frac=0.08).index, "Debt_Ratio"] = np.nan

# 7. Inject Duplicates (Task 3 requirement)
duplicate_rows = df.iloc[[1, 2, 3, 4, 5]].copy()
df = pd.concat([df, duplicate_rows], ignore_index=True)

# Save to CSV
df.to_csv("your_dataset.csv", index=False)
print("Successfully generated 'your_dataset.csv' with all required assignment edge cases!")

# Convert 'Age' back to numeric and coerce 'Unknown' to NaN
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")
# Convert 'Department' to category
df["Department"] = df["Department"].astype("category")

# Use 'Department' as your categorical column
categorical_col = "Department"

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# ==========================================
# Task 1: Load the dataset
# ==========================================
print("--- Task 1: Data Loading ---")
# TODO: Replace with your actual file path
df = pd.read_csv('your_dataset.csv')

print("First 5 rows:")
display(df.head())
print("\nData Types:")
print(df.dtypes)
print("\nDataFrame Shape:", df.shape)

# ==========================================
# Task 2: Null value analysis
# ==========================================
print("\n--- Task 2: Null Value Analysis ---")
null_counts = df.isnull().sum()
null_percentages = (null_counts / df.shape[0]) * 100
null_summary = pd.DataFrame({'Null Count': null_counts, 'Null Percentage': null_percentages})
print("Null Percentage Table:")
print(null_summary)

print("\nColumns exceeding 20% null rate:")
print(null_percentages[null_percentages > 20])

# Impute numeric columns with < 20% nulls
numeric_cols = df.select_dtypes(include=[np.number]).columns
for col in numeric_cols:
    if 0 < null_percentages[col] <= 20:
        median_val = df[col].median()
        df[col] = df[col].fillna(median_val)
        print(f"Filled nulls in '{col}' with median: {median_val}")

# ==========================================
# Task 3: Duplicate detection and removal
# ==========================================
print("\n--- Task 3: Duplicate Detection ---")
duplicate_count = df.duplicated().sum()
print(f"Number of duplicate rows: {duplicate_count}")

# Store null percentage before dropping to compare
null_pct_before = (df.isnull().sum() / df.shape[0]) * 100

df = df.drop_duplicates()
print(f"Rows remaining after dropping duplicates: {df.shape[0]}")

null_pct_after = (df.isnull().sum() / df.shape[0]) * 100
null_pct_change = null_pct_after - null_pct_before
print("\nChange in null percentage after duplicate removal:")
print(null_pct_change[null_pct_change != 0].dropna())

# ==========================================
# Task 4: Data type correction
# ==========================================
print("\n--- Task 4: Data Type Correction ---")
print("Memory usage BEFORE conversion:")
print(df.memory_usage(deep=True).sum(), "bytes")

# TODO: Replace 'numeric_col_as_object' with a column that needs numeric conversion
# df['numeric_col_as_object'] = pd.to_numeric(df['numeric_col_as_object'], errors='coerce')

# TODO: Replace 'string_col_to_category' with a repetitive string column
# df['string_col_to_category'] = df['string_col_to_category'].astype('category')

print("Memory usage AFTER conversion:")
print(df.memory_usage(deep=True).sum(), "bytes")

# ==========================================
# Task 5: Descriptive statistics and skewness
# ==========================================
print("\n--- Task 5: Descriptive Stats & Skewness ---")
print("Descriptive Statistics:")
display(df.describe())

print("\nSkewness of numeric columns:")
skewness = df[numeric_cols].skew()
print(skewness)

highest_skew_col = skewness.abs().idxmax()
print(f"\nColumn with highest absolute skewness: {highest_skew_col} (Skew: {skewness[highest_skew_col]:.4f})")

# ==========================================
# Task 6: Outlier detection with IQR
# ==========================================
print("\n--- Task 6: Outlier Detection ---")
# TODO: Choose two numeric columns for outlier detection
cols_for_outliers = [numeric_cols[0], numeric_cols[1]]

for col in cols_for_outliers:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]
    print(f"Column '{col}': {len(outliers)} outliers detected.")

# ==========================================
# Task 7: Visualizations
# ==========================================
print("\n--- Task 7: Visualizations ---")
plt.figure(figsize=(15, 10))

# 1. Line plot
plt.subplot(2, 3, 1)
# TODO: Replace 'numeric_cols[0]' with your desired column
plt.plot(df.index, df[numeric_cols[0]])
plt.title(f'Line Plot of {numeric_cols[0]}')
plt.xlabel('Index')
plt.ylabel(numeric_cols[0])

# 2. Bar chart
plt.subplot(2, 3, 2)
# TODO: Replace categorical/numeric cols
# categorical_col = 'your_cat_col'
# df.groupby(categorical_col)[numeric_cols[1]].mean().plot.bar()
# plt.title(f'Mean {numeric_cols[1]} by {categorical_col}')

# 3. Histogram of most skewed column
plt.subplot(2, 3, 3)
sns.histplot(df[highest_skew_col], bins=20)
plt.title(f'Histogram of {highest_skew_col}')

# 4. Scatter plot
plt.subplot(2, 3, 4)
# TODO: Replace with two columns you expect to be correlated
sns.scatterplot(x=df[numeric_cols[0]], y=df[numeric_cols[1]])
plt.title(f'Scatter: {numeric_cols[0]} vs {numeric_cols[1]}')

# 5. Box plot
plt.subplot(2, 3, 5)
# TODO: Replace 'your_cat_col' and 'numeric_cols[0]'
# sns.boxplot(x=df['your_cat_col'], y=df[numeric_cols[0]])
# plt.title('Box plot by Category')

plt.tight_layout()
plt.show()

# ==========================================
# Task 8: Correlation heat map
# ==========================================
print("\n--- Task 8: Correlation Heat Map ---")
pearson_corr = df[numeric_cols].corr()

plt.figure(figsize=(10, 8))
sns.heatmap(pearson_corr, annot=True, cmap='coolwarm', fmt=".2f")
plt.title("Pearson Correlation Heatmap")
plt.show()

# Extracting highest absolute correlation
corr_unstacked = pearson_corr.abs().unstack()
corr_unstacked = corr_unstacked[corr_unstacked < 1.0] # Exclude self-correlation
top_corr_pair = corr_unstacked.idxmax()
print(f"Highest absolute correlation pair: {top_corr_pair} (Value: {corr_unstacked.max():.4f})")

# ==========================================
# Task 9a: Imputation strategy comparison
# ==========================================
print("\n--- Task 9a: Imputation Strategy Comparison ---")
top_2_skewed = skewness.abs().nlargest(2).index

for col in top_2_skewed:
    col_mean = df[col].mean()
    col_median = df[col].median()
    print(f"Column '{col}': Mean = {col_mean:.4f}, Median = {col_median:.4f}")

    # Impute remaining nulls (if any) with the median
    df[col] = df[col].fillna(col_median)

print("\nNulls remaining in top skewed columns after imputation:")
print(df[top_2_skewed].isnull().sum())

# ==========================================
# Task 9b: Spearman rank correlation
# ==========================================
print("\n--- Task 9b: Spearman Rank Correlation ---")
spearman_corr = df[numeric_cols].corr(method='spearman')

print("Spearman Correlation Matrix:")
display(spearman_corr)

diff_matrix = (spearman_corr - pearson_corr).abs()
print("\nAbsolute Difference Matrix (|Spearman - Pearson|):")
display(diff_matrix)

# Get top 3 column pairs with largest difference
diff_unstacked = diff_matrix.unstack()
diff_unstacked = diff_unstacked[diff_unstacked < 1.0].drop_duplicates()
top_3_diffs = diff_unstacked.nlargest(3)
print("\nTop 3 column pairs with largest |Spearman - Pearson| difference:")
print(top_3_diffs)

# ==========================================
# Task 9c: Grouped aggregation
# ==========================================
print("\n--- Task 9c: Grouped Aggregation ---")
# TODO: Replace with your actual categorical and numeric column
cat_col = df.select_dtypes(include=['category', 'object']).columns[0] # taking first string col as fallback
num_col = numeric_cols[0]

grouped_agg = df.groupby(cat_col)[num_col].agg(['mean', 'std', 'count'])
print(f"Grouped Aggregation ({num_col} grouped by {cat_col}):")
print(grouped_agg)

# ==========================================
# Task 10: Save clean dataset
# ==========================================
print("\n--- Task 10: Saving Data ---")
df.to_csv('cleaned_data.csv', index=False)
print("Data saved successfully to 'cleaned_data.csv'")